### ISSUE TITLE
questions / clue less

### ISSUE THREAD

**Issue by ozra** [ysbaddaden/crystal-alpine#1]
I'll be the first to admit I have very little experience with containers and what not. I'm not sure I'm on the right trail here, but my mission is to have statically compiled crystal binaries, kinda "work everywhere".
I cloned this repo, ran `vagrant up --provision`, but I get some things like:
```
WARNING: Ignoring file:///home/vagrant/packages/testing/x86_64/APKINDEX.tar.gz: No such file or directory
==> alpine64: ERROR: unsatisfiable constraints:
==> alpine64:   crystal (missing):
==> alpine64:     required by: world[crystal]
```
Both for alpine32 and alpine64.

[ed:] Of course:
```
==> alpine32: WARNING: Ignoring file:///home/vagrant/packages/testing/x86/APKINDEX.tar.gz: No such file or directory
```
for alpine32...
[/ed]

What am I doing wrong?

**Comment by ysbaddaden** [comment]
The reason is that I do have the packages available locally (under `packages/`) and mounted inside the Alpine guest as `/home/vagrant/packages` which is where packages are built. I never bothered to change the provisioning to initialy target my repository. Please follow the steps explained there to had it: https://dl.dropboxusercontent.com/u/53345358/alpine/setup.txt

Thought you won't be capable to statically link a Crystal compiler under Alpine, unless you recompile the required packages to enable static libraries (LLVM, Boehm GC, etc).

**Comment by ozra** [comment]
Alright, thanks, now it found crystal apk.

So, if compiling all deps against musl and generating static libs, it should be possible to build static crystal that works "everywhere"?

**Comment by ysbaddaden** [comment]
Yes.

**Comment by ozra** [comment]
Thanks for the help!
